# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imgcat < Formula
  desc "Display images and gifs in your terminal"
  homepage ""
  version "1.0.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielgatis/imgcat/releases/download/v1.0.23/imgcat_1.0.23_darwin_amd64.zip"
      sha256 "ce2f84e2149950f3c7f20a5dca2ed255617900b9329391b9e605e6bfd0947485"

      def install
        bin.install "imgcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielgatis/imgcat/releases/download/v1.0.23/imgcat_1.0.23_darwin_arm64.zip"
      sha256 "e0fe1270810371115221f118f7d99e0994d00dc44e0d3e566d4727cd48850868"

      def install
        bin.install "imgcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/danielgatis/imgcat/releases/download/v1.0.23/imgcat_1.0.23_linux_amd64.tar.gz"
        sha256 "96429087f26fdbe8ec8adbd94db94362ffb99c2f85ca0300a72d04bd53ce11e3"

        def install
          bin.install "imgcat"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/danielgatis/imgcat/releases/download/v1.0.23/imgcat_1.0.23_linux_arm64.tar.gz"
        sha256 "a80d204b9be5760c7354f7ee6bd0ee29a8c946cc5096913798701ad91a1aec92"

        def install
          bin.install "imgcat"
        end
      end
    end
  end
end
