# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imgcat < Formula
  desc "Display images and gifs in your terminal"
  homepage ""
  version "1.0.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielgatis/imgcat/releases/download/v1.0.23/imgcat_1.0.23_darwin_amd64.zip"
      sha256 "30e3b1401c63060fe9bd7c25e0b5865b156a99a4cfbc5f8f5a40eb504a8de6a1"

      def install
        bin.install "imgcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielgatis/imgcat/releases/download/v1.0.23/imgcat_1.0.23_darwin_arm64.zip"
      sha256 "b7344bc3d599869e977218a6b7e0f8937df44777152a8c089bd6dd367169a93a"

      def install
        bin.install "imgcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/danielgatis/imgcat/releases/download/v1.0.23/imgcat_1.0.23_linux_amd64.tar.gz"
        sha256 "0a82ad05080b5577b973040fb1b449ddd7a303693f976cb8bd326370c835440a"

        def install
          bin.install "imgcat"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/danielgatis/imgcat/releases/download/v1.0.23/imgcat_1.0.23_linux_arm64.tar.gz"
        sha256 "4eb27154eba27a47f5a700c7b0d76e3a04acdbdfd04c30d320cfbef7291334e9"

        def install
          bin.install "imgcat"
        end
      end
    end
  end
end
