# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imgcat < Formula
  desc "Display images and gifs in your terminal"
  homepage ""
  version "1.0.20"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielgatis/imgcat/releases/download/v1.0.20/imgcat_1.0.20_Darwin_x86_64.tar.gz"
      sha256 "7cc13b9f512ef6871bd75233ce166e55de28414ad6b53b8734bad41575838ff3"

      def install
        bin.install "imgcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielgatis/imgcat/releases/download/v1.0.20/imgcat_1.0.20_Darwin_arm64.tar.gz"
      sha256 "a40b8a878f29224906d469a198fb764c326e893a7bd8fd648b683d493a37dd1d"

      def install
        bin.install "imgcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/danielgatis/imgcat/releases/download/v1.0.20/imgcat_1.0.20_Linux_x86_64.tar.gz"
      sha256 "d0941ad206a11e4a9c942ffb7d3598615d1663a6b79c2c197e6ad61f8558f420"

      def install
        bin.install "imgcat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielgatis/imgcat/releases/download/v1.0.20/imgcat_1.0.20_Linux_arm64.tar.gz"
      sha256 "362edb4bed735067f2d960de4ce7308e4e5986f28234c09e438e03d91e3671c3"

      def install
        bin.install "imgcat"
      end
    end
  end
end
